package com.rick.management.car.spring.persit.domain;

// Generated Mar 24, 2014 3:02:09 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChiTietDatXe generated by hbm2java
 */
@Entity
@Table(name = "chi_tiet_dat_xe", catalog = "management_rental_car")
public class ChiTietDatXe implements java.io.Serializable {

	private Integer chiTietDatXeId;
	private DatXe datXe;
	private DmXe dmXe;
	private Date ngayThue;
	private Date ngayTra;
	private Integer soLuong;
	private Double soTien;
	private String tinhTrang;

	public ChiTietDatXe() {
	}

	public ChiTietDatXe(DmXe dmXe) {
		this.dmXe = dmXe;
	}

	public ChiTietDatXe(DatXe datXe, DmXe dmXe, Date ngayThue, Date ngayTra,
			Integer soLuong, Double soTien, String tinhTrang) {
		this.datXe = datXe;
		this.dmXe = dmXe;
		this.ngayThue = ngayThue;
		this.ngayTra = ngayTra;
		this.soLuong = soLuong;
		this.soTien = soTien;
		this.tinhTrang = tinhTrang;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "chi_tiet_dat_xe_id", unique = true, nullable = false)
	public Integer getChiTietDatXeId() {
		return this.chiTietDatXeId;
	}

	public void setChiTietDatXeId(Integer chiTietDatXeId) {
		this.chiTietDatXeId = chiTietDatXeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dat_xe_id")
	public DatXe getDatXe() {
		return this.datXe;
	}

	public void setDatXe(DatXe datXe) {
		this.datXe = datXe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dm_xe_id", nullable = false)
	public DmXe getDmXe() {
		return this.dmXe;
	}

	public void setDmXe(DmXe dmXe) {
		this.dmXe = dmXe;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngay_thue", length = 19)
	public Date getNgayThue() {
		return this.ngayThue;
	}

	public void setNgayThue(Date ngayThue) {
		this.ngayThue = ngayThue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngay_tra", length = 19)
	public Date getNgayTra() {
		return this.ngayTra;
	}

	public void setNgayTra(Date ngayTra) {
		this.ngayTra = ngayTra;
	}

	@Column(name = "so_luong")
	public Integer getSoLuong() {
		return this.soLuong;
	}

	public void setSoLuong(Integer soLuong) {
		this.soLuong = soLuong;
	}

	@Column(name = "so_tien", precision = 22, scale = 0)
	public Double getSoTien() {
		return this.soTien;
	}

	public void setSoTien(Double soTien) {
		this.soTien = soTien;
	}

	@Column(name = "tinh_trang", length = 50)
	public String getTinhTrang() {
		return this.tinhTrang;
	}

	public void setTinhTrang(String tinhTrang) {
		this.tinhTrang = tinhTrang;
	}

}
