package com.rick.management.car.spring.persit.domain;

// Generated Mar 24, 2014 3:02:09 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HangXe generated by hbm2java
 */
@Entity
@Table(name = "hang_xe", catalog = "management_rental_car")
public class HangXe implements java.io.Serializable {

	private Integer hangXeId;
	private String tenHangXe;
	private Set<LoaiXe> loaiXes = new HashSet<LoaiXe>(0);

	public HangXe() {
	}

	public HangXe(String tenHangXe) {
		this.tenHangXe = tenHangXe;
	}

	public HangXe(String tenHangXe, Set<LoaiXe> loaiXes) {
		this.tenHangXe = tenHangXe;
		this.loaiXes = loaiXes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "hang_xe_id", unique = true, nullable = false)
	public Integer getHangXeId() {
		return this.hangXeId;
	}

	public void setHangXeId(Integer hangXeId) {
		this.hangXeId = hangXeId;
	}

	@Column(name = "ten_hang_xe", nullable = false, length = 50)
	public String getTenHangXe() {
		return this.tenHangXe;
	}

	public void setTenHangXe(String tenHangXe) {
		this.tenHangXe = tenHangXe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hangXe")
	public Set<LoaiXe> getLoaiXes() {
		return this.loaiXes;
	}

	public void setLoaiXes(Set<LoaiXe> loaiXes) {
		this.loaiXes = loaiXes;
	}

}
