package com.rick.management.car.spring.persit.domain;

// Generated Mar 24, 2014 3:02:09 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LoaiXe generated by hbm2java
 */
@Entity
@Table(name = "loai_xe", catalog = "management_rental_car")
public class LoaiXe implements java.io.Serializable {

	private Integer loaiXeId;
	private HangXe hangXe;
	private String tenLoaiXe;
	private Integer soCho;
	private Set<DmXe> dmXes = new HashSet<DmXe>(0);

	public LoaiXe() {
	}

	public LoaiXe(HangXe hangXe, String tenLoaiXe, Integer soCho,
			Set<DmXe> dmXes) {
		this.hangXe = hangXe;
		this.tenLoaiXe = tenLoaiXe;
		this.soCho = soCho;
		this.dmXes = dmXes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "loai_xe_id", unique = true, nullable = false)
	public Integer getLoaiXeId() {
		return this.loaiXeId;
	}

	public void setLoaiXeId(Integer loaiXeId) {
		this.loaiXeId = loaiXeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hang_xe_id")
	public HangXe getHangXe() {
		return this.hangXe;
	}

	public void setHangXe(HangXe hangXe) {
		this.hangXe = hangXe;
	}

	@Column(name = "ten_loai_xe", length = 50)
	public String getTenLoaiXe() {
		return this.tenLoaiXe;
	}

	public void setTenLoaiXe(String tenLoaiXe) {
		this.tenLoaiXe = tenLoaiXe;
	}

	@Column(name = "so_cho")
	public Integer getSoCho() {
		return this.soCho;
	}

	public void setSoCho(Integer soCho) {
		this.soCho = soCho;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiXe")
	public Set<DmXe> getDmXes() {
		return this.dmXes;
	}

	public void setDmXes(Set<DmXe> dmXes) {
		this.dmXes = dmXes;
	}

}
