package com.rick.management.car.spring.persit.domain;

// Generated Mar 24, 2014 3:02:09 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "management_rental_car")
public class User implements java.io.Serializable {

	private Integer quanliId;
	private String userName;
	private String password;
	private String hoTen;
	private Date ngaySinh;
	private Short gioiTinh;
	private String dienThoai;
	private long cmnd;
	private String email;
	private String diachi;
	private Set<NhapXe> nhapXes = new HashSet<NhapXe>(0);
	private Set<DmQuyen> dmQuyens = new HashSet<DmQuyen>(0);
	private Set<DatXe> datXes = new HashSet<DatXe>(0);

	public User() {
	}

	public User(String userName, String password, long cmnd) {
		this.userName = userName;
		this.password = password;
		this.cmnd = cmnd;
	}

	public User(String userName, String password, String hoTen, Date ngaySinh,
			Short gioiTinh, String dienThoai, long cmnd, String email,
			String diachi, Set<NhapXe> nhapXes, Set<DmQuyen> dmQuyens,
			Set<DatXe> datXes) {
		this.userName = userName;
		this.password = password;
		this.hoTen = hoTen;
		this.ngaySinh = ngaySinh;
		this.gioiTinh = gioiTinh;
		this.dienThoai = dienThoai;
		this.cmnd = cmnd;
		this.email = email;
		this.diachi = diachi;
		this.nhapXes = nhapXes;
		this.dmQuyens = dmQuyens;
		this.datXes = datXes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "quanli_id", unique = true, nullable = false)
	public Integer getQuanliId() {
		return this.quanliId;
	}

	public void setQuanliId(Integer quanliId) {
		this.quanliId = quanliId;
	}

	@Column(name = "user_name", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "password", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ho_ten", length = 50)
	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngay_sinh", length = 19)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "gioi_tinh")
	public Short getGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(Short gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	@Column(name = "dien_thoai", length = 13)
	public String getDienThoai() {
		return this.dienThoai;
	}

	public void setDienThoai(String dienThoai) {
		this.dienThoai = dienThoai;
	}

	@Column(name = "cmnd", nullable = false, precision = 15, scale = 0)
	public long getCmnd() {
		return this.cmnd;
	}

	public void setCmnd(long cmnd) {
		this.cmnd = cmnd;
	}

	@Column(name = "email", length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "diachi")
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<NhapXe> getNhapXes() {
		return this.nhapXes;
	}

	public void setNhapXes(Set<NhapXe> nhapXes) {
		this.nhapXes = nhapXes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<DmQuyen> getDmQuyens() {
		return this.dmQuyens;
	}

	public void setDmQuyens(Set<DmQuyen> dmQuyens) {
		this.dmQuyens = dmQuyens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<DatXe> getDatXes() {
		return this.datXes;
	}

	public void setDatXes(Set<DatXe> datXes) {
		this.datXes = datXes;
	}

}
